service: speedybot-serverless-experiment
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.speedybot_serverless
    events:
      - httpApi:
          path: /
          method: post
